name: oto_asistan
description: AI destekli otomobil sağlık ve rehberlik asistanı
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0

  # UI & Tasarım
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7

  # Araçlar
  intl: ^0.19.0
  uuid: ^4.2.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0 # .env yönetimi için eklendi
  
  # AI (Gemini API)
  google_generative_ai: ^0.4.0

  # Grafikler
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
  assets:
    - .env # .env dosyasının projeye dahil edilmesi şarttır